export const nowPlayingMovies = {
  dates: {
    maximum: "2024-08-28",
    minimum: "2024-07-17",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
      genre_ids: [28, 35, 878],
      id: 533535,
      original_language: "en",
      original_title: "Deadpool \u0026 Wolverine",
      overview:
        "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
      popularity: 7253.796,
      poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      release_date: "2024-07-24",
      title: "Deadpool \u0026 Wolverine",
      video: false,
      vote_average: 7.778,
      vote_count: 2136,
    },
    {
      adult: false,
      backdrop_path: "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
      genre_ids: [16, 10751, 12, 35],
      id: 1022789,
      original_language: "en",
      original_title: "Inside Out 2",
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      popularity: 3553.993,
      poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
      release_date: "2024-06-11",
      title: "Inside Out 2",
      video: false,
      vote_average: 7.643,
      vote_count: 2607,
    },
    {
      adult: false,
      backdrop_path: "/58D6ZAvOKxlHjyX9S8qNKSBE9Y.jpg",
      genre_ids: [28, 12, 18, 53],
      id: 718821,
      original_language: "en",
      original_title: "Twisters",
      overview:
        "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
      popularity: 2752.7,
      poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
      release_date: "2024-07-10",
      title: "Twisters",
      video: false,
      vote_average: 7.075,
      vote_count: 926,
    },
    {
      adult: false,
      backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
      genre_ids: [16, 10751, 35, 28],
      id: 519182,
      original_language: "en",
      original_title: "Despicable Me 4",
      overview:
        "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
      popularity: 2348.416,
      poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
      release_date: "2024-06-20",
      title: "Despicable Me 4",
      video: false,
      vote_average: 7.312,
      vote_count: 1134,
    },
    {
      adult: false,
      backdrop_path: "/okVLmXL5y18dfN2R4ufMZEGaeCd.jpg",
      genre_ids: [28, 80],
      id: 1160018,
      original_language: "hi",
      original_title: "Kill",
      overview:
        "When an army commando finds out his true love is engaged against her will, he boards a New Dehli-bound train in a daring quest to derail the arranged marriage. But when a gang of knife-wielding thieves begin to terrorize innocent passengers on his train, the commando takes them on himself in a death-defying kill-spree to save those around him — turning what should have been a typical commute into an adrenaline-fueled thrill ride.",
      popularity: 1658.56,
      poster_path: "/m2zXTuNPkywdYLyWlVyJZW2QOJH.jpg",
      release_date: "2024-07-03",
      title: "Kill",
      video: false,
      vote_average: 7.019,
      vote_count: 77,
    },
    {
      adult: false,
      backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
      genre_ids: [27, 878],
      id: 945961,
      original_language: "en",
      original_title: "Alien: Romulus",
      overview:
        "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
      popularity: 1569.607,
      poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
      release_date: "2024-08-13",
      title: "Alien: Romulus",
      video: false,
      vote_average: 7.259,
      vote_count: 405,
    },
    {
      adult: false,
      backdrop_path: "/9BQqngPfwpeAfK7c2H3cwIFWIVR.jpg",
      genre_ids: [10749, 18],
      id: 1079091,
      original_language: "en",
      original_title: "It Ends with Us",
      overview:
        "Lily Bloom overcomes a traumatic childhood to embark on a new life in Boston and chase a lifelong dream of opening her own business. A chance meeting with charming neurosurgeon Ryle Kincaid sparks an intense connection, but as the two fall deeply in love, Lily begins to see sides of Ryle that remind her of her parents' relationship.",
      popularity: 1394.747,
      poster_path: "/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg",
      release_date: "2024-08-07",
      title: "It Ends with Us",
      video: false,
      vote_average: 7.1,
      vote_count: 116,
    },
    {
      adult: false,
      backdrop_path: "/2MJIfQDA9orY3uVSnzExogbdhH6.jpg",
      genre_ids: [16, 35, 12, 10751],
      id: 831815,
      original_language: "en",
      original_title: "Saving Bikini Bottom: The Sandy Cheeks Movie",
      overview:
        "When Bikini Bottom is scooped from the ocean, scientific squirrel Sandy Cheeks and her pal SpongeBob SquarePants saddle up for Texas to save their town.",
      popularity: 1271.629,
      poster_path: "/30YnfZdMNIV7noWLdvmcJS0cbnQ.jpg",
      release_date: "2024-08-01",
      title: "Saving Bikini Bottom: The Sandy Cheeks Movie",
      video: false,
      vote_average: 6.432,
      vote_count: 154,
    },
    {
      adult: false,
      backdrop_path: "/h9YlRHAZWOWtGonllmj6JJg1FrE.jpg",
      genre_ids: [28, 12, 16, 10751, 14],
      id: 588648,
      original_language: "zh",
      original_title: "Dragonkeeper",
      overview:
        "Set in Han Imperial China, the plot follows the adventures of enslaved girl Ping with ancient dragon Long Danzi. Dragons had been banished from the kingdom. Ping, an orphan, finds one of the last remaining dragon eggs. Palace guards force Ping to run away in order to return the dragon egg to the ocean and save all dragons from extinction. Ping discovers that she is a true Dragonkeeper.",
      popularity: 1263.18,
      poster_path: "/ggZGnJLzO3BTu7ysuuIzou3Oex5.jpg",
      release_date: "2024-04-11",
      title: "Dragonkeeper",
      video: false,
      vote_average: 7.197,
      vote_count: 38,
    },
    {
      adult: false,
      backdrop_path: "/QflfyU07MiQXSqTUCmG9Xfq0Ws.jpg",
      genre_ids: [28, 18, 10749],
      id: 1281826,
      original_language: "en",
      original_title: "One Fast Move",
      overview:
        "A dishonorably discharged soldier seeks out his estranged father to help him pursue his dream of becoming a professional motorcycle racer. While training, he meets a small-town, aspiring singer and a motorcycle shop owner who begin to break down the walls his father’s absence had built up.",
      popularity: 1109.341,
      poster_path: "/hdBUjfbdr1ymS0kycAT7qguOmWA.jpg",
      release_date: "2024-08-07",
      title: "One Fast Move",
      video: false,
      vote_average: 6.819,
      vote_count: 83,
    },
    {
      adult: false,
      backdrop_path: "/1wP1phHo2CROOqzv7Azs0MT5esU.jpg",
      genre_ids: [16, 35, 10751, 12, 28],
      id: 748783,
      original_language: "en",
      original_title: "The Garfield Movie",
      overview:
        "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
      popularity: 1009.283,
      poster_path: "/xYduFGuch9OwbCOEUiamml18ZoB.jpg",
      release_date: "2024-04-30",
      title: "The Garfield Movie",
      video: false,
      vote_average: 7.185,
      vote_count: 794,
    },
    {
      adult: false,
      backdrop_path: "/qQqEq11QsXdSTmYs3M7D5bxFHJg.jpg",
      genre_ids: [28, 35, 80],
      id: 1059064,
      original_language: "en",
      original_title: "The Instigators",
      overview:
        "Rory and Cobby are unlikely partners thrown together for a heist. But when it goes awry, they team up to outrun police, backward bureaucrats, and a vengeful crime boss.",
      popularity: 999.439,
      poster_path: "/thI9pM7Qu43f42sOOl5wy75UAo.jpg",
      release_date: "2024-08-02",
      title: "The Instigators",
      video: false,
      vote_average: 6.429,
      vote_count: 197,
    },
    {
      adult: false,
      backdrop_path: "/lyEuje8cKjbWliYUGrOaoHVmc1R.jpg",
      genre_ids: [28, 35, 12],
      id: 1002088,
      original_language: "ko",
      original_title: "크로스",
      overview:
        "In the ultimate test of marriage, an agent-turned-househusband gets tangled in a perilous mission with his detective wife, who's clueless about his past.",
      popularity: 785.005,
      poster_path: "/aE9WqOApdRYsowsGE0118dyA4c9.jpg",
      release_date: "2024-08-05",
      title: "Mission: Cross",
      video: false,
      vote_average: 7.029,
      vote_count: 52,
    },
    {
      adult: false,
      backdrop_path: "/pzFbYJfqGKlGxOsDIIsUi6YxVQ.jpg",
      genre_ids: [28, 35, 878],
      id: 1094138,
      original_language: "en",
      original_title: "Jackpot!",
      overview:
        "In the near future, a 'Grand Lottery' has been established - the catch: kill the winner before sundown to legally claim their multi-billion dollar jackpot. When Katie Kim mistakenly finds herself with the winning ticket, she reluctantly joins forces with amateur lottery protection agent Noel Cassidy who must get her to sundown in exchange for a piece of her prize.",
      popularity: 732.705,
      poster_path: "/wWWlclyWf4PLq9hOf8X5joVEJ6r.jpg",
      release_date: "2024-08-13",
      title: "Jackpot!",
      video: false,
      vote_average: 6.485,
      vote_count: 194,
    },
    {
      adult: false,
      backdrop_path: "/zB0g0VaRKHfRrvBT4ouHK5W967W.jpg",
      genre_ids: [10749, 35],
      id: 956842,
      original_language: "en",
      original_title: "Fly Me to the Moon",
      overview:
        "Sparks fly in all directions as marketing maven Kelly Jones, brought in to fix NASA's public image, wreaks havoc on Apollo 11 launch director Cole Davis' already difficult task of putting a man on the moon. When the White House deems the mission too important to fail, Jones is directed to stage a fake moon landing as backup, and the countdown truly begins.",
      popularity: 699.691,
      poster_path: "/gjk8YdXpItoC1in53FCrZMFIuBx.jpg",
      release_date: "2024-07-10",
      title: "Fly Me to the Moon",
      video: false,
      vote_average: 7.071,
      vote_count: 281,
    },
    {
      adult: false,
      backdrop_path: "/c3rwwFFVbkyEI6wPtpPd9lvovPW.jpg",
      genre_ids: [28, 36],
      id: 1311550,
      original_language: "en",
      original_title: "House of Ga'a",
      overview:
        "At the height of the Oyo Empire, the ferocious Bashorun Ga'a became more powerful than the kings he enthroned, only to be undone by his own blood.",
      popularity: 692.799,
      poster_path: "/6yK9hmS641NMwRkR1wWAALWI34t.jpg",
      release_date: "2024-07-26",
      title: "House of Ga'a",
      video: false,
      vote_average: 5.932,
      vote_count: 37,
    },
    {
      adult: false,
      backdrop_path: "/xYyPLClpJiA5pq687pGjRel5qgf.jpg",
      genre_ids: [28, 53],
      id: 1064375,
      original_language: "en",
      original_title: "Paradox Effect",
      overview:
        "An innocent woman is forced to confront a dangerous kingpin who has kidnapped her young daughter and is holding her for ransom. She teams up with a corrupt Interpol agent, whose son is also being held hostage, to rip off various criminals to raise the ransom to save their offspring. Together they have one hour to save their families from the wrath of bigwig.",
      popularity: 658.471,
      poster_path: "/koJFEW997sLjpu4e7wmFioA2mhL.jpg",
      release_date: "2024-06-27",
      title: "Paradox Effect",
      video: false,
      vote_average: 6.444,
      vote_count: 18,
    },
    {
      adult: false,
      backdrop_path: "/yhEu41kat5sZ5QhCdZnh3Vypu5V.jpg",
      genre_ids: [27, 53, 35],
      id: 1225377,
      original_language: "en",
      original_title: "The Mouse Trap",
      overview:
        "It's Alex's 21st Birthday, but she's stuck at the amusement arcade on a late shift so her friends decide to surprise her, but a masked killer dressed as Mickey Mouse decides to play a game of his own with them which she must survive.",
      popularity: 650.506,
      poster_path: "/3ovFaFeojLFIl5ClqhtgYMDS8sE.jpg",
      release_date: "2024-08-23",
      title: "The Mouse Trap",
      video: false,
      vote_average: 2.6,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/wkPPRIducGfsbaUPsWfw0MCQdX7.jpg",
      genre_ids: [28, 35, 12],
      id: 1051891,
      original_language: "en",
      original_title: "Thelma",
      overview:
        "When 93-year-old Thelma Post gets duped by a phone scammer pretending to be her grandson, she sets out on a treacherous quest across the city to reclaim what was taken from her.",
      popularity: 615.249,
      poster_path: "/rUcuageYgv9SsJoWuc0seRWG6JC.jpg",
      release_date: "2024-06-21",
      title: "Thelma",
      video: false,
      vote_average: 7.049,
      vote_count: 72,
    },
    {
      adult: false,
      backdrop_path: "/6Vbm2nHxHMlZZ199fmZtMytpFvK.jpg",
      genre_ids: [28, 53, 35, 18],
      id: 1309923,
      original_language: "es",
      original_title: "No negociable",
      overview:
        "Hostage negotiator Alan Bender is called to rescue the president from a kidnapping, only to find himself also mediating to save his wife and marriage.",
      popularity: 527.974,
      poster_path: "/bHQG4UsLMFCy91gfLAFRpnCOPdP.jpg",
      release_date: "2024-07-25",
      title: "Non Negotiable",
      video: false,
      vote_average: 6.006,
      vote_count: 78,
    },
  ],
  total_pages: 179,
  total_results: 3573,
};

export const popularMovies = {
  page: 3,
  results: [
    {
      adult: false,
      backdrop_path: "/hofnlIyF6bePkgQOpcuRWLvzf15.jpg",
      genre_ids: [16, 10751, 14],
      id: 14836,
      original_language: "en",
      original_title: "Coraline",
      overview:
        "Wandering her rambling old house in her boring new town, 11-year-old Coraline discovers a hidden door to a strangely idealized version of her life. In order to stay in the fantasy, she must make a frighteningly real sacrifice.",
      popularity: 425.634,
      poster_path: "/4jeFXQYytChdZYE9JYO7Un87IlW.jpg",
      release_date: "2009-02-05",
      title: "Coraline",
      video: false,
      vote_average: 7.878,
      vote_count: 7743,
    },
    {
      adult: false,
      backdrop_path: "/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg",
      genre_ids: [28, 35],
      id: 1048241,
      original_language: "en",
      original_title: "My Spy The Eternal City",
      overview:
        "JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.",
      popularity: 384.123,
      poster_path: "/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg",
      release_date: "2024-07-18",
      title: "My Spy The Eternal City",
      video: false,
      vote_average: 6.716,
      vote_count: 241,
    },
    {
      adult: false,
      backdrop_path: "/vwwHt1hNvPpAUEFW6YHdhy9jJmY.jpg",
      genre_ids: [28, 12, 16, 35, 14],
      id: 1085046,
      original_language: "en",
      original_title: "超级英雄美猴王：齐天儿",
      overview:
        "Shimmy, a monkey newly discover superhero powers and learns how to control his extraordinary transformative abilities and prevent powerful demonic forces from sending the universe into chaos.",
      popularity: 483.518,
      poster_path: "/ktvSdBzYts4voUO0FJG5O6FOcPI.jpg",
      release_date: "2023-04-21",
      title: "Shimmy: The First Monkey King",
      video: false,
      vote_average: 6.571,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: "/iafs5DG5fGq7ef0acl3xlX4BFrs.jpg",
      genre_ids: [18, 10770],
      id: 1219685,
      original_language: "fr",
      original_title: "Un père idéal",
      overview:
        "Michel, the jovial owner of the only café in a small Normandy town, sees his life turned upside down when his teenage daughter is murdered. The community has his back but soon rumor spreads and Michel is singled out. From the ideal father, he becomes the ideal culprit.",
      popularity: 430.104,
      poster_path: "/4xJd3uwtL1vCuZgEfEc8JXI9Uyx.jpg",
      release_date: "2024-04-21",
      title: "An Ideal Father",
      video: false,
      vote_average: 6.532,
      vote_count: 79,
    },
    {
      adult: false,
      backdrop_path: "/en971MEXui9diirXlogOrPKmsEn.jpg",
      genre_ids: [28, 12, 35],
      id: 293660,
      original_language: "en",
      original_title: "Deadpool",
      overview:
        "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
      popularity: 414.045,
      poster_path: "/3E53WEZJqP6aM84D8CckXx4pIHw.jpg",
      release_date: "2016-02-09",
      title: "Deadpool",
      video: false,
      vote_average: 7.619,
      vote_count: 30544,
    },
    {
      adult: false,
      backdrop_path: "/8fNBsXpgMvqk75SPsZzTmIqSRxY.jpg",
      genre_ids: [27, 53],
      id: 646683,
      original_language: "en",
      original_title: "The Exorcism",
      overview:
        "A troubled actor begins to unravel while shooting a supernatural horror film, leading his estranged daughter to wonder if he's slipping back into his past addictions or if there's something more sinister at play.",
      popularity: 384.104,
      poster_path: "/ar2h87jlTfMlrDZefR3VFz1SfgH.jpg",
      release_date: "2024-05-30",
      title: "The Exorcism",
      video: false,
      vote_average: 4.585,
      vote_count: 117,
    },
    {
      adult: false,
      backdrop_path: "/xKJTWGvheOMMlTHgrjN18KaD9Ra.jpg",
      genre_ids: [27, 53],
      id: 1174618,
      original_language: "en",
      original_title: "Alice in Terrorland",
      overview:
        "A recently bereaved teenage girl goes to live with her aunt in a secluded woodland house, unaware that sinister forces lurk within.",
      popularity: 353.646,
      poster_path: "/5XJGvr8g9jkmN6KUIOQOj2iE6K4.jpg",
      release_date: "2023-12-26",
      title: "Alice in Terrorland",
      video: false,
      vote_average: 5.951,
      vote_count: 132,
    },
    {
      adult: false,
      backdrop_path: "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
      genre_ids: [28, 12, 53, 80],
      id: 7451,
      original_language: "en",
      original_title: "xXx",
      overview:
        'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
      popularity: 423.207,
      poster_path: "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
      release_date: "2002-08-09",
      title: "xXx",
      video: false,
      vote_average: 5.935,
      vote_count: 4153,
    },
    {
      adult: false,
      backdrop_path: "/9Y9wTgrMk4G1YNPDDekNk7dybwx.jpg",
      genre_ids: [28, 12, 10752],
      id: 1152624,
      original_language: "en",
      original_title: "3 Days in Malay",
      overview:
        "Marines stationed at an airfield in Malay during WWII get wind of a coming raid by the Japanese. Unable to get reinforcements approved, they engage in a harrowing 3-day battle against enemy forces.",
      popularity: 375.853,
      poster_path: "/hqnfqeCILvgKGWKOut5lVdxdeJh.jpg",
      release_date: "2023-08-11",
      title: "3 Days in Malay",
      video: false,
      vote_average: 4.917,
      vote_count: 24,
    },
    {
      adult: false,
      backdrop_path: "/7ks7A3mAO7twDOvBVE4cR8LaIM8.jpg",
      genre_ids: [16, 28, 18],
      id: 1104844,
      original_language: "ja",
      original_title: "劇場版ブルーロック -EPISODE 凪-",
      overview:
        "One day, Nagi Seishiro receives an invitation to the mysterious BLUE LOCK Project. What awaits him there is an encounter with the finest strikers assembled from across the country. Nagi's dream of becoming the best, alongside Mikage Reo, will take this prodigy to a world he's never known.",
      popularity: 402.096,
      poster_path: "/ae434jM5NG2kKX1rRkG5giMhpPI.jpg",
      release_date: "2024-04-19",
      title: "BLUE LOCK THE MOVIE -EPISODE NAGI-",
      video: false,
      vote_average: 8.422,
      vote_count: 32,
    },
    {
      adult: false,
      backdrop_path: "/wPNI1fd18z5TKBOK9Mv9Rfjb0j0.jpg",
      genre_ids: [53, 18, 28, 80],
      id: 729165,
      original_language: "en",
      original_title: "Out of Exile",
      overview:
        "Recently paroled thief Gabriel Russell tries to balance his life and mend a troubled family as an FBI agent hunts him down, along with his crew after a botched armored car robbery.",
      popularity: 343.541,
      poster_path: "/jgF5XaXnJmOgMxulhy2k1f9LNNc.jpg",
      release_date: "2023-01-20",
      title: "Out of Exile",
      video: false,
      vote_average: 6.306,
      vote_count: 36,
    },
    {
      adult: false,
      backdrop_path: "/iwkWvcXcP8M4r9HLglhVEhgGyVu.jpg",
      genre_ids: [28, 18, 27, 53],
      id: 1001311,
      original_language: "fr",
      original_title: "Sous la Seine",
      overview:
        "In order to save Paris from an international bloodbath, a grieving scientist is forced to face her tragic past when a giant shark appears in the Seine.",
      popularity: 325.527,
      poster_path: "/qZPLK5ktRKa3CL4sKRZtj8UlPYc.jpg",
      release_date: "2024-06-04",
      title: "Under Paris",
      video: false,
      vote_average: 6.056,
      vote_count: 1039,
    },
    {
      adult: false,
      backdrop_path: "/viKEEaaCaZ0hZ2nGuvIEozlLooL.jpg",
      genre_ids: [80, 27, 9648, 53],
      id: 1023922,
      original_language: "en",
      original_title: "MaXXXine",
      overview:
        "In 1980s Hollywood, adult film star and aspiring actress Maxine Minx finally gets her big break. But as a mysterious killer stalks the starlets of Hollywood, a trail of blood threatens to reveal her sinister past.",
      popularity: 389.846,
      poster_path: "/ArvoFK6nlouZRxYmtIOUzKIrg90.jpg",
      release_date: "2024-07-04",
      title: "MaXXXine",
      video: false,
      vote_average: 6.377,
      vote_count: 351,
    },
    {
      adult: false,
      backdrop_path: "/tIpd7vvjoNyG6CAVqSL9gJqJSTy.jpg",
      genre_ids: [28, 53, 80],
      id: 857553,
      original_language: "en",
      original_title: "Johnny \u0026 Clyde",
      overview:
        "Johnny and Clyde are two serial killers who are madly in love and on an endless crime spree. Alana (Megan Fox) is the confident and cunning owner of a prosperous casino that generates tens of millions of dollars each year. Johnny and Clyde decide to assemble a ragtag group of criminals and misfits to steal from Alana's casino and pull off the heist of the century. Unfortunately for Johnny and Clyde's crew, Alana has a deadly weapon at her disposal – the monstrous slasher spirit known as Bakwas.",
      popularity: 302.194,
      poster_path: "/cdfdR90WYCTQmYoQ0aDRZP8I2IL.jpg",
      release_date: "2023-03-23",
      title: "Johnny \u0026 Clyde",
      video: false,
      vote_average: 4.758,
      vote_count: 33,
    },
    {
      adult: false,
      backdrop_path: "/iAlsYg6dlv1fvOBypM7SldIS1Wl.jpg",
      genre_ids: [80, 53],
      id: 1032823,
      original_language: "en",
      original_title: "Trap",
      overview:
        "A father and teen daughter attend a pop concert, where they realize they're at the center of a dark and sinister event.",
      popularity: 364.806,
      poster_path: "/mWV2fNBkSTW67dIotVTXDYZhNBj.jpg",
      release_date: "2024-07-31",
      title: "Trap",
      video: false,
      vote_average: 6.348,
      vote_count: 358,
    },
    {
      adult: false,
      backdrop_path: "/e6FWExcyn1rxcfYSOrApm94Rga0.jpg",
      genre_ids: [27, 53],
      id: 1175038,
      original_language: "en",
      original_title: "Stranger in the Woods",
      overview:
        "Olivia and her friends go on a vacation. After Olivia nearly drowns with a slit wrist in her bathtub after her fiancé's funeral, her friends suspect that she tried to kill herself, but she believes someone attacked her.",
      popularity: 299.957,
      poster_path: "/qcrbiVMOkAaOyha8BqyVDQCTwh6.jpg",
      release_date: "2024-02-14",
      title: "Stranger in the Woods",
      video: false,
      vote_average: 6.284,
      vote_count: 81,
    },
    {
      adult: false,
      backdrop_path: "/rrwt0u1rW685u9bJ9ougg5HJEHC.jpg",
      genre_ids: [28, 35, 80],
      id: 280180,
      original_language: "en",
      original_title: "Beverly Hills Cop: Axel F",
      overview:
        "Forty years after his unforgettable first case in Beverly Hills, Detroit cop Axel Foley returns to do what he does best: solve crimes and cause chaos.",
      popularity: 302.587,
      poster_path: "/zszRKfzjM5jltiq8rk6rasKVpUv.jpg",
      release_date: "2024-06-20",
      title: "Beverly Hills Cop: Axel F",
      video: false,
      vote_average: 6.841,
      vote_count: 858,
    },
    {
      adult: false,
      backdrop_path: "/pZFuow2rweIqyNHz6xZSxnLVmMc.jpg",
      genre_ids: [27],
      id: 1097150,
      original_language: "en",
      original_title: "Deliver Us",
      overview:
        "When a nun in a remote convent claims immaculate conception, the Vatican sends a team of priests to investigate, concerned about an ancient prophecy that a woman will give birth to twin boys: one the Messiah, the other the Antichrist.",
      popularity: 312.815,
      poster_path: "/uoKUTwvHvSVHWjSM4RhCh6rKL0U.jpg",
      release_date: "2023-08-30",
      title: "Deliver Us",
      video: false,
      vote_average: 5.641,
      vote_count: 46,
    },
    {
      adult: false,
      backdrop_path: "/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg",
      genre_ids: [16, 28, 12, 35, 10751],
      id: 940551,
      original_language: "en",
      original_title: "Migration",
      overview:
        "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
      popularity: 324.228,
      poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
      release_date: "2023-12-06",
      title: "Migration",
      video: false,
      vote_average: 7.5,
      vote_count: 1644,
    },
    {
      adult: false,
      backdrop_path: "/oSJV6nAfHzyE9v6oEAXmDjbko00.jpg",
      genre_ids: [14, 12],
      id: 943344,
      original_language: "zh",
      original_title: "地底怪物",
      overview:
        "Near a remote town, the repeated dumping of toxic waste causes an underground cave dweller to mutate into a hideous monster. A construction team that is digging a tunnel accidentally disturb the creature's habitat causing it to attack.",
      popularity: 311.921,
      poster_path: "/lWVwWRLqpS1OaNg7KT0ZecSW0PK.jpg",
      release_date: "2023-04-27",
      title: "Underground Monster",
      video: false,
      vote_average: 4.4,
      vote_count: 9,
    },
  ],
  total_pages: 45629,
  total_results: 912568,
};

export const topRatedMovies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/avedvodAZUcwqevBfm8p4G2NziQ.jpg",
      genre_ids: [18, 80],
      id: 278,
      original_language: "en",
      original_title: "The Shawshank Redemption",
      overview:
        "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
      popularity: 139.874,
      poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
      release_date: "1994-09-23",
      title: "The Shawshank Redemption",
      video: false,
      vote_average: 8.705,
      vote_count: 26665,
    },
    {
      adult: false,
      backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
      genre_ids: [18, 80],
      id: 238,
      original_language: "en",
      original_title: "The Godfather",
      overview:
        "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
      popularity: 315.134,
      poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
      release_date: "1972-03-14",
      title: "The Godfather",
      video: false,
      vote_average: 8.7,
      vote_count: 20226,
    },
    {
      adult: false,
      backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
      genre_ids: [18, 80],
      id: 240,
      original_language: "en",
      original_title: "The Godfather Part II",
      overview:
        "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
      popularity: 103.576,
      poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
      release_date: "1974-12-20",
      title: "The Godfather Part II",
      video: false,
      vote_average: 8.6,
      vote_count: 12203,
    },
    {
      adult: false,
      backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
      genre_ids: [18, 36, 10752],
      id: 424,
      original_language: "en",
      original_title: "Schindler's List",
      overview:
        "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
      popularity: 96.436,
      poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
      release_date: "1993-12-15",
      title: "Schindler's List",
      video: false,
      vote_average: 8.565,
      vote_count: 15611,
    },
    {
      adult: false,
      backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
      genre_ids: [18],
      id: 389,
      original_language: "en",
      original_title: "12 Angry Men",
      overview:
        "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
      popularity: 61.693,
      poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
      release_date: "1957-04-10",
      title: "12 Angry Men",
      video: false,
      vote_average: 8.5,
      vote_count: 8451,
    },
    {
      adult: false,
      backdrop_path: "/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg",
      genre_ids: [16, 10751, 14],
      id: 129,
      original_language: "ja",
      original_title: "千と千尋の神隠し",
      overview:
        "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
      popularity: 101.834,
      poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
      release_date: "2001-07-20",
      title: "Spirited Away",
      video: false,
      vote_average: 8.537,
      vote_count: 16228,
    },
    {
      adult: false,
      backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
      genre_ids: [35, 18, 10749],
      id: 19404,
      original_language: "hi",
      original_title: "दिलवाले दुल्हनिया ले जायेंगे",
      overview:
        "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
      popularity: 36.832,
      poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
      release_date: "1995-10-20",
      title: "Dilwale Dulhania Le Jayenge",
      video: false,
      vote_average: 8.535,
      vote_count: 4414,
    },
    {
      adult: false,
      backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
      genre_ids: [18, 28, 80, 53],
      id: 155,
      original_language: "en",
      original_title: "The Dark Knight",
      overview:
        "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
      popularity: 157.524,
      poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      release_date: "2008-07-16",
      title: "The Dark Knight",
      video: false,
      vote_average: 8.516,
      vote_count: 32396,
    },
    {
      adult: false,
      backdrop_path: "/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg",
      genre_ids: [35, 53, 18],
      id: 496243,
      original_language: "ko",
      original_title: "기생충",
      overview:
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      popularity: 85.671,
      poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      release_date: "2019-05-30",
      title: "Parasite",
      video: false,
      vote_average: 8.506,
      vote_count: 17909,
    },
    {
      adult: false,
      backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
      genre_ids: [14, 18, 80],
      id: 497,
      original_language: "en",
      original_title: "The Green Mile",
      overview:
        "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
      popularity: 120.309,
      poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
      release_date: "1999-12-10",
      title: "The Green Mile",
      video: false,
      vote_average: 8.506,
      vote_count: 17108,
    },
    {
      adult: false,
      backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
      genre_ids: [16, 10749, 18],
      id: 372058,
      original_language: "ja",
      original_title: "君の名は。",
      overview:
        "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
      popularity: 87.248,
      poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
      release_date: "2016-08-26",
      title: "Your Name.",
      video: false,
      vote_average: 8.488,
      vote_count: 11193,
    },
    {
      adult: false,
      backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
      genre_ids: [53, 80],
      id: 680,
      original_language: "en",
      original_title: "Pulp Fiction",
      overview:
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      popularity: 117.927,
      poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
      release_date: "1994-09-10",
      title: "Pulp Fiction",
      video: false,
      vote_average: 8.488,
      vote_count: 27521,
    },
    {
      adult: false,
      backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
      genre_ids: [12, 14, 28],
      id: 122,
      original_language: "en",
      original_title: "The Lord of the Rings: The Return of the King",
      overview:
        "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
      popularity: 135.987,
      poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      release_date: "2003-12-17",
      title: "The Lord of the Rings: The Return of the King",
      video: false,
      vote_average: 8.481,
      vote_count: 23785,
    },
    {
      adult: false,
      backdrop_path: "/i9qxG4UVgfX4AdMGnfRzMYEowLQ.jpg",
      genre_ids: [12, 36, 28, 18, 10749, 53],
      id: 1084736,
      original_language: "fr",
      original_title: "Le Comte de Monte-Cristo",
      overview:
        "Edmond Dantes becomes the target of a sinister plot and is arrested on his wedding day for a crime he did not commit. After 14 years in the island prison of Château d’If, he manages a daring escape. Now rich beyond his dreams, he assumes the identity of the Count of Monte-Cristo and exacts his revenge on the three men who betrayed him.",
      popularity: 78.83,
      poster_path: "/aHRUsFln97FlIdsvYKFT3z5ubYE.jpg",
      release_date: "2024-06-28",
      title: "The Count of Monte-Cristo",
      video: false,
      vote_average: 8.475,
      vote_count: 454,
    },
    {
      adult: false,
      backdrop_path: "/ghgfzbEV7kbpbi1O8eIILKVXEA8.jpg",
      genre_ids: [35, 18, 10749],
      id: 13,
      original_language: "en",
      original_title: "Forrest Gump",
      overview:
        "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
      popularity: 90.072,
      poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
      release_date: "1994-06-23",
      title: "Forrest Gump",
      video: false,
      vote_average: 8.5,
      vote_count: 27035,
    },
    {
      adult: false,
      backdrop_path: "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
      genre_ids: [18, 80],
      id: 769,
      original_language: "en",
      original_title: "GoodFellas",
      overview:
        "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
      popularity: 97.849,
      poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
      release_date: "1990-09-12",
      title: "GoodFellas",
      video: false,
      vote_average: 8.463,
      vote_count: 12633,
    },
    {
      adult: false,
      backdrop_path: "/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg",
      genre_ids: [37],
      id: 429,
      original_language: "it",
      original_title: "Il buono, il brutto, il cattivo",
      overview:
        "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
      popularity: 79.896,
      poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
      release_date: "1966-12-22",
      title: "The Good, the Bad and the Ugly",
      video: false,
      vote_average: 8.462,
      vote_count: 8438,
    },
    {
      adult: false,
      backdrop_path: "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
      genre_ids: [28, 18],
      id: 346,
      original_language: "ja",
      original_title: "七人の侍",
      overview:
        "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
      popularity: 55.727,
      poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
      release_date: "1954-04-26",
      title: "Seven Samurai",
      video: false,
      vote_average: 8.5,
      vote_count: 3585,
    },
    {
      adult: false,
      backdrop_path: "/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg",
      genre_ids: [10751, 18],
      id: 667257,
      original_language: "es",
      original_title: "Cosas imposibles",
      overview:
        "After the death of her abusive husband, Matilde finds her new best friend in Miguel, her young, insecure, and disoriented neighbor.",
      popularity: 33.905,
      poster_path: "/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg",
      release_date: "2021-06-17",
      title: "Impossible Things",
      video: false,
      vote_average: 8.5,
      vote_count: 380,
    },
    {
      adult: false,
      backdrop_path: "/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg",
      genre_ids: [16, 18, 10752],
      id: 12477,
      original_language: "ja",
      original_title: "火垂るの墓",
      overview:
        "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
      popularity: 0.067,
      poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
      release_date: "1988-04-16",
      title: "Grave of the Fireflies",
      video: false,
      vote_average: 8.457,
      vote_count: 5366,
    },
  ],
  total_pages: 479,
  total_results: 9574,
};

export const upcomingMovies = {
  dates: {
    maximum: "2024-09-18",
    minimum: "2024-08-28",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/okVLmXL5y18dfN2R4ufMZEGaeCd.jpg",
      genre_ids: [28, 80],
      id: 1160018,
      original_language: "hi",
      original_title: "Kill",
      overview:
        "When an army commando finds out his true love is engaged against her will, he boards a New Dehli-bound train in a daring quest to derail the arranged marriage. But when a gang of knife-wielding thieves begin to terrorize innocent passengers on his train, the commando takes them on himself in a death-defying kill-spree to save those around him — turning what should have been a typical commute into an adrenaline-fueled thrill ride.",
      popularity: 1658.56,
      poster_path: "/m2zXTuNPkywdYLyWlVyJZW2QOJH.jpg",
      release_date: "2024-07-03",
      title: "Kill",
      video: false,
      vote_average: 7.019,
      vote_count: 77,
    },
    {
      adult: false,
      backdrop_path: "/9BQqngPfwpeAfK7c2H3cwIFWIVR.jpg",
      genre_ids: [10749, 18],
      id: 1079091,
      original_language: "en",
      original_title: "It Ends with Us",
      overview:
        "Lily Bloom overcomes a traumatic childhood to embark on a new life in Boston and chase a lifelong dream of opening her own business. A chance meeting with charming neurosurgeon Ryle Kincaid sparks an intense connection, but as the two fall deeply in love, Lily begins to see sides of Ryle that remind her of her parents' relationship.",
      popularity: 1394.747,
      poster_path: "/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg",
      release_date: "2024-08-07",
      title: "It Ends with Us",
      video: false,
      vote_average: 7.1,
      vote_count: 116,
    },
    {
      adult: false,
      backdrop_path: "/y6Z8aogJjuAk9rWVIl1xpV5GENt.jpg",
      genre_ids: [28, 53],
      id: 1129598,
      original_language: "en",
      original_title: "Prey",
      overview:
        "A young couple is compelled to leave their Christian missionary station in the Kalahari Desert after being threatened with death by an extremist militant gang. After crashing their aircraft they must battle man and beast for their lives.",
      popularity: 1211.616,
      poster_path: "/5wAlO5zZ3IyzLBAf7cp5WejalmG.jpg",
      release_date: "2024-03-15",
      title: "Prey",
      video: false,
      vote_average: 6.517,
      vote_count: 176,
    },
    {
      adult: false,
      backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
      genre_ids: [27, 878],
      id: 945961,
      original_language: "en",
      original_title: "Alien: Romulus",
      overview:
        "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
      popularity: 1569.607,
      poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
      release_date: "2024-08-13",
      title: "Alien: Romulus",
      video: false,
      vote_average: 7.281,
      vote_count: 397,
    },
    {
      adult: false,
      backdrop_path: "/tqSg1hHiSWhHAhnjDhhevaFGsP0.jpg",
      genre_ids: [28, 18],
      id: 1066262,
      original_language: "en",
      original_title: "The Convert",
      overview:
        "Munro, a soldier turned lay preacher, comes to New Zealand to minister to the first British colonists, but he is converted by the powerful chief Maianui to serve a different purpose.",
      popularity: 804.43,
      poster_path: "/e5ZqqPlhKstzB4geibpZh38w7Pq.jpg",
      release_date: "2024-03-14",
      title: "The Convert",
      video: false,
      vote_average: 6.255,
      vote_count: 47,
    },
    {
      adult: false,
      backdrop_path: "/yhEu41kat5sZ5QhCdZnh3Vypu5V.jpg",
      genre_ids: [27, 53, 35],
      id: 1225377,
      original_language: "en",
      original_title: "The Mouse Trap",
      overview:
        "It's Alex's 21st Birthday, but she's stuck at the amusement arcade on a late shift so her friends decide to surprise her, but a masked killer dressed as Mickey Mouse decides to play a game of his own with them which she must survive.",
      popularity: 650.506,
      poster_path: "/3ovFaFeojLFIl5ClqhtgYMDS8sE.jpg",
      release_date: "2024-08-23",
      title: "The Mouse Trap",
      video: false,
      vote_average: 2.6,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/wkPPRIducGfsbaUPsWfw0MCQdX7.jpg",
      genre_ids: [28, 35, 12],
      id: 1051891,
      original_language: "en",
      original_title: "Thelma",
      overview:
        "When 93-year-old Thelma Post gets duped by a phone scammer pretending to be her grandson, she sets out on a treacherous quest across the city to reclaim what was taken from her.",
      popularity: 615.249,
      poster_path: "/rUcuageYgv9SsJoWuc0seRWG6JC.jpg",
      release_date: "2024-06-21",
      title: "Thelma",
      video: false,
      vote_average: 7.049,
      vote_count: 72,
    },
    {
      adult: false,
      backdrop_path: "/8fNBsXpgMvqk75SPsZzTmIqSRxY.jpg",
      genre_ids: [27, 53],
      id: 646683,
      original_language: "en",
      original_title: "The Exorcism",
      overview:
        "A troubled actor begins to unravel while shooting a supernatural horror film, leading his estranged daughter to wonder if he's slipping back into his past addictions or if there's something more sinister at play.",
      popularity: 384.104,
      poster_path: "/ar2h87jlTfMlrDZefR3VFz1SfgH.jpg",
      release_date: "2024-05-30",
      title: "The Exorcism",
      video: false,
      vote_average: 4.585,
      vote_count: 117,
    },
    {
      adult: false,
      backdrop_path: "/viKEEaaCaZ0hZ2nGuvIEozlLooL.jpg",
      genre_ids: [80, 27, 9648, 53],
      id: 1023922,
      original_language: "en",
      original_title: "MaXXXine",
      overview:
        "In 1980s Hollywood, adult film star and aspiring actress Maxine Minx finally gets her big break. But as a mysterious killer stalks the starlets of Hollywood, a trail of blood threatens to reveal her sinister past.",
      popularity: 389.846,
      poster_path: "/ArvoFK6nlouZRxYmtIOUzKIrg90.jpg",
      release_date: "2024-07-04",
      title: "MaXXXine",
      video: false,
      vote_average: 6.378,
      vote_count: 353,
    },
    {
      adult: false,
      backdrop_path: "/iAlsYg6dlv1fvOBypM7SldIS1Wl.jpg",
      genre_ids: [80, 53],
      id: 1032823,
      original_language: "en",
      original_title: "Trap",
      overview:
        "A father and teen daughter attend a pop concert, where they realize they're at the center of a dark and sinister event.",
      popularity: 364.806,
      poster_path: "/mWV2fNBkSTW67dIotVTXDYZhNBj.jpg",
      release_date: "2024-07-31",
      title: "Trap",
      video: false,
      vote_average: 6.3,
      vote_count: 358,
    },
    {
      adult: false,
      backdrop_path: "/59AJ2w9tKRSbBpnxKfB5UyIg6Jf.jpg",
      genre_ids: [27, 53],
      id: 1010600,
      original_language: "en",
      original_title: "The Strangers: Chapter 1",
      overview:
        "After their car breaks down in an eerie small town, a young couple are forced to spend the night in a remote cabin. Panic ensues as they are terrorized by three masked strangers who strike with no mercy and seemingly no motives.",
      popularity: 302.88,
      poster_path: "/oYsCNpW4k7Pd7ac3uQfBhr2ihtW.jpg",
      release_date: "2024-05-15",
      title: "The Strangers: Chapter 1",
      video: false,
      vote_average: 5.93,
      vote_count: 272,
    },
    {
      adult: false,
      backdrop_path: "/1KJtjg3MQFnrfd7NXfs11z4HLwD.jpg",
      genre_ids: [53, 27],
      id: 804616,
      original_language: "en",
      original_title: "Something in the Water",
      overview:
        "Reunited at an exotic destination wedding, five girlfriends decide to rent a boat to spend a day together along the paradise-like coast. Their friendship is put to the ultimate test when they find themselves stranded in open water fighting for their lives against sharks and mother nature as they desperately try to survive.",
      popularity: 451.751,
      poster_path: "/1iWGGxHEwswZGvPSoMZlLFf0PNq.jpg",
      release_date: "2024-03-22",
      title: "Something in the Water",
      video: false,
      vote_average: 6.024,
      vote_count: 103,
    },
    {
      adult: false,
      backdrop_path: "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
      genre_ids: [27],
      id: 938614,
      original_language: "en",
      original_title: "Late Night with the Devil",
      overview:
        "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
      popularity: 217.81,
      poster_path: "/jGY62i0D0zitaGz4Ema7vTEYIXw.jpg",
      release_date: "2024-03-19",
      title: "Late Night with the Devil",
      video: false,
      vote_average: 7.322,
      vote_count: 699,
    },
    {
      adult: false,
      backdrop_path: "/vblTCXOWUQGSc837vgbhDRi4HSc.jpg",
      genre_ids: [28, 80, 35, 53],
      id: 955555,
      original_language: "ko",
      original_title: "범죄도시 3",
      overview:
        "Detective Ma Seok-do changes his affiliation from the Geumcheon Police Station to the Metropolitan Investigation Team, in order to eradicate Japanese gangsters who enter Korea to commit heinous crimes.",
      popularity: 222.006,
      poster_path: "/lW6IHrtaATxDKYVYoQGU5sh0OVm.jpg",
      release_date: "2023-05-31",
      title: "The Roundup: No Way Out",
      video: false,
      vote_average: 7.3,
      vote_count: 388,
    },
    {
      adult: false,
      backdrop_path: "/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg",
      genre_ids: [12, 14, 28],
      id: 120,
      original_language: "en",
      original_title: "The Lord of the Rings: The Fellowship of the Ring",
      overview:
        "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
      popularity: 134.983,
      poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
      release_date: "2001-12-18",
      title: "The Lord of the Rings: The Fellowship of the Ring",
      video: false,
      vote_average: 8.414,
      vote_count: 24718,
    },
    {
      adult: false,
      backdrop_path: "/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg",
      genre_ids: [27, 53],
      id: 1111873,
      original_language: "en",
      original_title: "Abigail",
      overview:
        "A group of criminals kidnaps a teenage ballet dancer, the daughter of a notorious gang leader, in order to obtain a ransom of $50 million, but over time, they discover that she is not just an ordinary girl. After the kidnappers begin to diminish, one by one, they discover, to their increasing horror, that they are locked inside with an unusual girl.",
      popularity: 175.053,
      poster_path: "/rx0Sg4cK5gO6QKkyI0JAGT5tLJb.jpg",
      release_date: "2024-04-16",
      title: "Abigail",
      video: false,
      vote_average: 6.839,
      vote_count: 962,
    },
    {
      adult: false,
      backdrop_path: "/Avtx5jsdPuDa091jvx2Lye3ygke.jpg",
      genre_ids: [80, 27, 53],
      id: 1226578,
      original_language: "en",
      original_title: "Longlegs",
      overview:
        "In pursuit of a serial killer, an FBI agent uncovers a series of occult clues that she must solve to end his terrifying killing spree.",
      popularity: 199.504,
      poster_path: "/5aj8vVGFwGVbQQs26ywhg4Zxk2L.jpg",
      release_date: "2024-07-10",
      title: "Longlegs",
      video: false,
      vote_average: 6.7,
      vote_count: 265,
    },
    {
      adult: false,
      backdrop_path: "/uFMIiNYUDHzo7YGSg5UUR7VLNma.jpg",
      genre_ids: [35],
      id: 1278099,
      original_language: "es",
      original_title: "El candidato honesto",
      overview:
        "A former idealistic leader turned corrupt politician is cursed by his grandmother on the eve of the presidential election, forcing him to be honest. Can he win without lies and what will be the conditions?",
      popularity: 151.446,
      poster_path: "/hmV5HPkbQuzgPo11Xm70CMQV3iZ.jpg",
      release_date: "2024-08-08",
      title: "El Candidato Honesto",
      video: false,
      vote_average: 6.125,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/kwGvFyRtGSSm8AFfnRNXoZTQmJj.jpg",
      genre_ids: [80, 18],
      id: 1008409,
      original_language: "en",
      original_title: "The Bikeriders",
      overview:
        "After a chance encounter, headstrong Kathy is drawn to Benny, member of Midwestern motorcycle club the Vandals. As the club transforms into a dangerous underworld of violence, Benny must choose between Kathy and his loyalty to the club.",
      popularity: 187.071,
      poster_path: "/qTb6sSRt8Pw96JTan8ezU2xO0FU.jpg",
      release_date: "2024-06-19",
      title: "The Bikeriders",
      video: false,
      vote_average: 6.9,
      vote_count: 431,
    },
    {
      adult: false,
      backdrop_path: "/fY3lD0jM5AoHJMunjGWqJ0hRteI.jpg",
      genre_ids: [878, 27, 28],
      id: 940721,
      original_language: "ja",
      original_title: "ゴジラ-1.0",
      overview:
        "In postwar Japan, Godzilla brings new devastation to an already scorched landscape. With no military intervention or government help in sight, the survivors must join together in the face of despair and fight back against an unrelenting horror.",
      popularity: 186.988,
      poster_path: "/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
      release_date: "2023-11-03",
      title: "Godzilla Minus One",
      video: false,
      vote_average: 7.582,
      vote_count: 2048,
    },
  ],
  total_pages: 55,
  total_results: 1086,
};

export const videos = {
  id: 533535,
  results: [
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Thank You",
      key: "hiGPEYgOdOs",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-08-16T20:03:13.000Z",
      id: "66c14b36150d42be109dd68b",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "All Time",
      key: "7dOcH4HN5fA",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-08-16T15:00:12.000Z",
      id: "66c14b19d0df06e09067347b",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Billion with a B",
      key: "PWdtBp5opqw",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-08-11T17:01:35.000Z",
      id: "66b9af137016621fb072d9a3",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Flame On",
      key: "YyVAwYCzuDk",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-08-10T16:00:34.000Z",
      id: "66b8433586cd6c9ecba7d971",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Popcorn and Jazz - 10 Hours",
      key: "83KmAr0aviA",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-08-09T21:34:49.000Z",
      id: "66c14aba5d3249246aa264ed",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Portal",
      key: "YBYOuQJ5Wno",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-08-09T16:00:35.000Z",
      id: "66b84340664dbd1625aab629",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Smashing",
      key: "qhAB4Y1VrO8",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-08-08T20:00:30.000Z",
      id: "66b57d92cf10bee8a8c5e71b",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Crying",
      key: "BId1AMHzItQ",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-08-03T16:00:10.000Z",
      id: "66aeb0171b9fd9ffd700f0de",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Watch Deadpool \u0026 Wolverine again and again and again and again and again and again and again and aga",
      key: "XBLJ6XOCBdY",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-08-03T01:30:56.000Z",
      id: "66aeb0310fbfa33dc400f0ca",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Smash",
      key: "QQ_jvHQM53o",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-08-02T17:00:29.000Z",
      id: "66aeaffeca4548c3b0b2caa3",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Score",
      key: "G9BWRaXdA-M",
      site: "YouTube",
      size: 1080,
      type: "Behind the Scenes",
      official: true,
      published_at: "2024-08-01T16:00:13.000Z",
      id: "66abbc6431e9e123f0507b07",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Dogpool Blooper",
      key: "45LohjMTJOM",
      site: "YouTube",
      size: 720,
      type: "Bloopers",
      official: true,
      published_at: "2024-07-30T22:16:28.000Z",
      id: "66abbdba264b247a70f8e1a7",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Thank You, Ray Chan",
      key: "3yPfmJMzVVY",
      site: "YouTube",
      size: 1080,
      type: "Behind the Scenes",
      official: true,
      published_at: "2024-07-30T16:00:03.000Z",
      id: "66a9ca1a08dbe0dcbb02fd39",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Ultimate Deadpool \u0026 Wolverine Celebration of Life",
      key: "9Bo_GQtD7vo",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-07-27T19:30:00.000Z",
      id: "66abbd0176c8d5d7bdf513a5",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Deadpool \u0026 Wolverine \u0026 Walking4Hope",
      key: "XfD4F9E3yX0",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-07-26T18:59:58.000Z",
      id: "66abbda5b268a2bdb45c8452",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Legendary",
      key: "dIpNpMfGxK8",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-07-25T19:01:59.000Z",
      id: "66a2a42585b44ccacd0a0ead",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Go",
      key: "eoFCmgF8Cjs",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-07-25T15:00:42.000Z",
      id: "66a29d6043ee488ea1e7fda0",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Official IMAX® Interview",
      key: "xdUc7qURlk4",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-07-25T04:50:34.000Z",
      id: "66a542ab4df5b07f2eb14759",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Pray",
      key: "u06vqfLcBas",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-07-24T15:49:03.000Z",
      id: "66a17e8db27abfd91335fc19",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Gear Up",
      key: "ETuda6ZGQkU",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-07-22T15:00:11.000Z",
      id: "66a192eab0908f4b03c812ac",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "This Friday",
      key: "UffWG-yFGgw",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-07-21T16:00:32.000Z",
      id: "669d9b6c428a1d9907779e39",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Deadpool \u0026 Wolverine in the Studio",
      key: "8BjXzXq3O5A",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: false,
      published_at: "2024-07-19T19:24:38.000Z",
      id: "669d9b872bc6164f536c8ad7",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Final Trailer",
      key: "Idh8n5XuYIA",
      site: "YouTube",
      size: 1080,
      type: "Trailer",
      official: true,
      published_at: "2024-07-19T14:00:23.000Z",
      id: "669a8ad15777920d534e6606",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Everyone",
      key: "C2QCuBX_byg",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-07-16T15:00:11.000Z",
      id: "6696909663380e4993be74c6",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Can’t Unsee It",
      key: "eN2rNIgy9JQ",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-07-15T11:00:01.000Z",
      id: "66953dd30c4c61e4f0168724",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Pumped",
      key: "eS-MpmL6fPc",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-07-12T16:00:44.000Z",
      id: "669199858b0fa7f0d7f19d42",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Deadpool \u0026 Wolverine \u0026 The Bachelorette",
      key: "S2sBNY9Wg8o",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-07-09T16:54:39.000Z",
      id: "6691f42d96716b2eee6e37ec",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Purpose",
      key: "Up6hJCihbL8",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-07-09T16:00:32.000Z",
      id: "668d6b74c0ea0ce79071bb41",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "World Tour",
      key: "LYuc1wDC318",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-07-06T22:34:28.000Z",
      id: "668b842b9f3f305a639a0670",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Shanghai Fan Event",
      key: "qoAYNhOWol8",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-07-03T02:38:06.000Z",
      id: "6684da33f6813e41938f1e20",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "LFG",
      key: "pABY-rpsfH4",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-07-01T16:00:49.000Z",
      id: "6684da156e16130ed075ee02",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Nice",
      key: "r3LisZEIK34",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-06-28T13:12:08.000Z",
      id: "667ee0b24729acf6c9007431",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Best Friends Day",
      key: "pn5fdK61o9c",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-06-08T16:00:40.000Z",
      id: "66669a7829661fd491dda78a",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "The Deadpool And Wolverine popcorn bucket has arrived",
      key: "ewkLcCQ1O-0",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-05-30T17:27:52.000Z",
      id: "665d8f00e6b575c8da81b176",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Tickets On Sale",
      key: "Esc_qtkULBE",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-05-21T15:00:18.000Z",
      id: "664dba2682a2ffadf09ac25c",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Heineken Silver - World-Class Light Beer for World-Class Bubs",
      key: "NebqFm0PoVw",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: false,
      published_at: "2024-05-20T20:26:36.000Z",
      id: "665bac89d42cd806d247e63e",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Get Tickets Now",
      key: "YLswizPsdYk",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-05-20T15:00:05.000Z",
      id: "664dba3f0bbde63500fd129c",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Tickets On Sale Now",
      key: "2I5aSPn_eYQ",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-05-20T13:00:00.000Z",
      id: "664dba4b28cc6d3f18f275c1",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Disclaimers",
      key: "pCdR7mgWT4s",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2024-05-19T16:50:11.000Z",
      id: "664db928e9b4172c3413f88f",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Official Trailer",
      key: "73_1biulkYk",
      site: "YouTube",
      size: 1080,
      type: "Trailer",
      official: true,
      published_at: "2024-04-22T13:00:09.000Z",
      id: "662668b62dda890149e08b9b",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Trailer Tomorrow",
      key: "umxRwIKOPA4",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-04-21T18:55:37.000Z",
      id: "6625761707faa2018799f02a",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Official Teaser",
      key: "uJMCNJP2ipI",
      site: "YouTube",
      size: 1080,
      type: "Teaser",
      official: true,
      published_at: "2024-02-11T23:36:49.000Z",
      id: "65c95bb74350110162e86f46",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Deadpool Update, Part Hugh",
      key: "Szj1iqYanFM",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2022-09-28T12:41:05.000Z",
      id: "633552dcbbd0b0007a5756f3",
    },
    {
      iso_639_1: "en",
      iso_3166_1: "US",
      name: "Deadpool Update",
      key: "Yd47Z8HYf0Y",
      site: "YouTube",
      size: 1080,
      type: "Featurette",
      official: true,
      published_at: "2022-09-27T21:00:53.000Z",
      id: "633546de528b2e007c0a4021",
    },
  ],
};
